export const testimonials = [
  {
    id: 1,
    name: "Dave Thompson",
    area: "Solihull",
    text: "Broke down on the A45 at 11pm and they were with me in 25 minutes. Sorted me right out.",
  },
  {
    id: 2,
    name: "Sarah Mitchell",
    area: "Redditch",
    text: "Used them to move my classic Mini to a new garage. Really careful with it, would use again.",
  },
  {
    id: 3,
    name: "Mark Williams",
    area: "Bromsgrove",
    text: "Car wouldn't start on a freezing morning. Quick response and fair price. Cheers lads.",
  },
  {
    id: 4,
    name: "Lisa Brennan",
    area: "Kings Heath",
    text: "Had an accident on the Pershore Road. They dealt with everything and dropped the car at the bodyshop for me.",
  },
  {
    id: 5,
    name: "James Patel",
    area: "Coventry",
    text: "Bought a car from a dealer and needed it collected. Arrived on time and the driver was really friendly.",
  },
  {
    id: 6,
    name: "Karen Hughes",
    area: "Worcester",
    text: "My daughter broke down late at night. They got to her quickly and made sure she was safe. Thank you.",
  },
  {
    id: 7,
    name: "Steve Robinson",
    area: "Dudley",
    text: "Moved my motorbike from storage to home. No scratches, no fuss. Proper job.",
  },
  {
    id: 8,
    name: "Rachel Edwards",
    area: "Harborne",
    text: "Gearbox went on the Hagley Road. They winched it onto the truck no problem. Reasonable price too.",
  },
  {
    id: 9,
    name: "Tony Clarke",
    area: "Sutton Coldfield",
    text: "Third time using Hadleys now. Always reliable and the lads know what they're doing.",
  },
  {
    id: 10,
    name: "Michelle Foster",
    area: "Tamworth",
    text: "Needed my van recovered after a bump. Insurance sorted, no hassle from my end.",
  },
  {
    id: 11,
    name: "Gary Simpson",
    area: "Wolverhampton",
    text: "Battery died at Merry Hill. Got me going again within the hour. Top service.",
  },
  {
    id: 12,
    name: "Emma Collins",
    area: "Leamington Spa",
    text: "Collected a project car for me from Birmingham. Turned up exactly when they said they would.",
  },
  {
    id: 13,
    name: "Chris Baker",
    area: "Erdington",
    text: "Had a flat tyre and couldn't get the wheel off. They sorted it roadside. Lifesavers.",
  },
  {
    id: 14,
    name: "Anita Sharma",
    area: "Small Heath",
    text: "Very professional. Explained everything clearly and the price was exactly what they quoted.",
  },
  {
    id: 15,
    name: "Paul Cartwright",
    area: "Walsall",
    text: "Engine overheated on the M6. Not the best situation but they made it easy to deal with.",
  },
  {
    id: 16,
    name: "Joanne Murphy",
    area: "Halesowen",
    text: "Bought a non-runner online and needed it delivered. Turned up on time and dropped it right where I wanted.",
  },
  {
    id: 17,
    name: "Ryan Doyle",
    area: "Cannock",
    text: "Locked my keys in the car like an idiot. They got me back in without any damage. Legend.",
  },
  {
    id: 18,
    name: "Helen Barker",
    area: "Stratford-upon-Avon",
    text: "Transported my elderly father's car after he had to stop driving. Handled it with real care.",
  },
  {
    id: 19,
    name: "Darren Price",
    area: "West Bromwich",
    text: "Been using Hadleys for years. Never let me down once. Wouldn't go anywhere else.",
  },
  {
    id: 20,
    name: "Fiona Walsh",
    area: "Droitwich",
    text: "Called at 6am after my car died on the way to work. They were out to me straight away.",
  },
]
